### ISSUE TITLE
Version 1.1.1 causes exception during Magento 2 `setup:upgrade` command execution.

### ISSUE THREAD

**Issue by Bar3nho** [klevu/logger#9]
The resource element in the acl.xml file does not have a title parameter:
https://github.com/klevu/logger/blob/c362f7504f5cc8bfdc0938508409e345a7befa2e/etc/acl.xml#L10
Causes `Element 'resource': The attribute 'title' is required but missing.` exception in M2. This prevents deployment after updating the logger to version 1.1.1.

**Comment by klevu** [comment]
@Bar3nho thank you for reporting this issue. 
We have release version 1.1.2 which contains the fix.
